
package partner.zeitarbeit;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PickupService", targetNamespace = "http://services.zeitarbeit.othr.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PickupService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<partner.zeitarbeit.Worker>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pickUp", targetNamespace = "http://services.zeitarbeit.othr.de/", className = "partner.zeitarbeit.PickUp")
    @ResponseWrapper(localName = "pickUpResponse", targetNamespace = "http://services.zeitarbeit.othr.de/", className = "partner.zeitarbeit.PickUpResponse")
    public List<Worker> pickUp(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0);

}
